version: "3.8"

services:
  api:
    environment:
      - ENV=production
      - DEBUG=false
    restart: unless-stopped

  frontend:
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  db:
    restart: unless-stopped
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data

  redis:
    restart: unless-stopped

  phi3-service:
    restart: unless-stopped

  gemma-service:
    restart: unless-stopped

  mistral-service:
    restart: unless-stopped

  nginx:
    restart: unless-stopped

volumes:
  postgres_data_prod:
